options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "asia-south1"
  _REPO: "portfolio"
  _SERVICE: "portfolio-api"
  _TAG: "latest"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${_TAG}",
        "./apps/api",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${_TAG}"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE}",
        "--image",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${_TAG}",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8000",
      ]